/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaceMapRouteImport } from './routes/space-map'
import { Route as IndexRouteImport } from './routes/index'

const SpaceMapRoute = SpaceMapRouteImport.update({
  id: '/space-map',
  path: '/space-map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/space-map': typeof SpaceMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/space-map': typeof SpaceMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/space-map': typeof SpaceMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/space-map'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/space-map'
  id: '__root__' | '/' | '/space-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpaceMapRoute: typeof SpaceMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/space-map': {
      id: '/space-map'
      path: '/space-map'
      fullPath: '/space-map'
      preLoaderRoute: typeof SpaceMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpaceMapRoute: SpaceMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
