/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpaceMapRouteImport } from './routes/space-map'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemsIndexRouteImport } from './routes/systems.index'
import { Route as SystemsSlugRouteImport } from './routes/systems.$slug'

const SpaceMapRoute = SpaceMapRouteImport.update({
  id: '/space-map',
  path: '/space-map',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIndexRoute = SystemsIndexRouteImport.update({
  id: '/systems/',
  path: '/systems/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsSlugRoute = SystemsSlugRouteImport.update({
  id: '/systems/$slug',
  path: '/systems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galaxy': typeof GalaxyRoute
  '/space-map': typeof SpaceMapRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galaxy': typeof GalaxyRoute
  '/space-map': typeof SpaceMapRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/systems': typeof SystemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galaxy': typeof GalaxyRoute
  '/space-map': typeof SpaceMapRoute
  '/systems/$slug': typeof SystemsSlugRoute
  '/systems/': typeof SystemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/galaxy' | '/space-map' | '/systems/$slug' | '/systems/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galaxy' | '/space-map' | '/systems/$slug' | '/systems'
  id:
    | '__root__'
    | '/'
    | '/galaxy'
    | '/space-map'
    | '/systems/$slug'
    | '/systems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalaxyRoute: typeof GalaxyRoute
  SpaceMapRoute: typeof SpaceMapRoute
  SystemsSlugRoute: typeof SystemsSlugRoute
  SystemsIndexRoute: typeof SystemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/space-map': {
      id: '/space-map'
      path: '/space-map'
      fullPath: '/space-map'
      preLoaderRoute: typeof SpaceMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/': {
      id: '/systems/'
      path: '/systems'
      fullPath: '/systems/'
      preLoaderRoute: typeof SystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$slug': {
      id: '/systems/$slug'
      path: '/systems/$slug'
      fullPath: '/systems/$slug'
      preLoaderRoute: typeof SystemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalaxyRoute: GalaxyRoute,
  SpaceMapRoute: SpaceMapRoute,
  SystemsSlugRoute: SystemsSlugRoute,
  SystemsIndexRoute: SystemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
